### PR TITLE
Push to Live

### PR DESCRIPTION
**Pull request by JustusCas**

### CODE REVIEW

**Comment by JustusCas** [comment]
@Norric1Admin @brockfanning does one of you know why this is falling?

**Comment by Norric1Admin** [comment]
@JustusCas Yes - the build has passed on one of the Travis checks and failed on the other: this is a common signature when layout or config files are changed (e.g. open-sdg version update), as `develop` and `master` are now trying to generate the site in different ways.

Merging the changes into `master` will resolve this, and future checks will pass. Hope this helps.

**Comment by JustusCas** [comment]
Thx @Norric1Admin, but apperantly the pushing to live is still falling as HTML-Proofer finds 139 failures. 

On example
`- ./_site/9-c-1/index.html
  *  image /assets/img/loading.gif does not have an alt attribute (line 664)`

Apparently the alt attribute is missing for the loading.gif, but in the code it's included.

**Comment by Norric1Admin** [comment]
Add `json: 'https://open-sdg.github.io/sdg-translations/translations-0.5.0.json'` into config and configprod. It may also help to remove goal.html, as this is one of the breaking changes for 0.5.3.

**Comment by brockfanning** [comment]
I don't think that Justus can remove goal.html, but he still needs to override that layout (in order to display the customized goal icons).

I would suggest looking for differences between _config.yml and _config_prod.yml. Here are some sections/lines in _config.yml that might need to be copied to _config_prod.yml:

* https://github.com/G205SDGs/sdg-indicators/blob/develop/_config.yml#L29
* https://github.com/G205SDGs/sdg-indicators/blob/develop/_config.yml#L34
* https://github.com/G205SDGs/sdg-indicators/blob/develop/_config.yml#L107

**Comment by JustusCas** [comment]
After I updated _config_prod.yml it is working. Thx @brockfanning

**Pull request merged**
